### ISSUE TITLE
where do I get the super mario 3d world + bowsers fury files?

### ISSUE THREAD

**Issue by DistortedBoyFriend** [jupahe64/Spotlight#13]
where do I get the super mario 3d world + bowsers fury files for spotlight? I have Spotlight downloaded but not sm3w (super mario 3d world) **where do I get it!!??**

**Comment by Lord-Giganticus** [comment]
“We cannot help you get the 3D World files”.
This statement on the README also applies to the switch version of the game. Sorry pal, but your only friend here will be google and luck.

**Comment by IonicPixels** [comment]
You must dump the game from your console
